version: "3"
services:
  facdb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BUILD_ENGINE=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/src
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgis/postgis:11-3.0-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
