version: "3"
services:
  facdb:
    container_name: facdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BUILD_ENGINE=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/src
    command: sleep infinity

volumes:
  postgres-data:
