version: "3"
services:
  facdb:
    container_name: facdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BUILD_ENGINE=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/src
    command: sleep infinity
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgis/postgis:11-3.0-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
