name: Comment testor
on:
  issues:
    types: [opened, edited]
jobs:
  getenv:
    if: contains(github.event.issue.title, '[')
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.initialize.outputs.VERSION }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - id: install
        run: |
          pip3 install csvtomd
          
      - id: initialize
        run: |
          curl -O https://edm-publishing.nyc3.digitaloceanspaces.com/db-gru-qaqc/addresses-spatial/latest/output/versions.csv
          
          VERSION=$(csvtomd versions.csv)
                    
          echo "::set-output name=VERSION::$VERSION"
  
  comment:
    needs: getenv
    runs-on: ubuntu-latest
    steps:
      - name: inspect file
        run: echo "${{ needs.getenv.outputs.VERSION }}"
        
      - name: comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ needs.getenv.outputs.VERSION }}
            
            does this actuall work???
