name: Comment testor
on:
  issues:
    types: [opened, edited]
jobs:
  getenv:
    if: contains(github.event.issue.title, '[')
    container:
      image: nycplanning/docker-geosupport:latest
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.initialize.outputs.VERSION }}
    steps:
      - id: install dependencies
        run: |
          pip3 install csvtomd
          
      - id: initialize
        run: |
          mkdir -p output
          echo "geosupport_major, $MAJOR" > output/versions.csv
          echo "geosupport_minor, $MINOR" >> output/versions.csv
          echo "geosupport_upad, $PATCH" >> output/versions.csv
          
          $VERSION=$(csvtomd output/versions.csv)
          
          echo $VERSION
          
          echo "::set-output name=VERSION::$VERSION"
  
  comment:
    needs: getenv
    runs-on: ubuntu-latest
    steps:
      - name: comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ needs.getenv.outputs.VERSION }}
          reactions: laugh
