on:
  release:
    type:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Deploying to GitHub Pages"
          echo "${{ github.sha }} ${{github.ref_name}}"
