name: Sync Develop to Main

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Reset main branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master
