name: Issue Openner

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        dataset: 
          - borough_boundaries
          - facilities 
          - council_districts
          - community_districts
          - inclusionary_housing
    steps:            
       - run: echo "${{ matrix.dataset }}"
      
    
