# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        name: Check if issue exists
        with: 
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
          const issues = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open'
          });
          const filtered = issues.data.filter(issue => issue.title === 'hi hellow')
          console.log(filtered.length);
