name: Issue Openner

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        dataset: 
          - borough_boundaries
          - facilities 
          - council_districts
          - community_districts
          - inclusionary_housing
    steps:            
       - run: echo "${{ matrix.dataset }}"
       - uses: actions/github-script@v3
         with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = `[publish] ${{ matrix.dataset }}`;
            const body = `
            ## Difference Detected Between `Production` and `Staging` in the following dataset(s)
            ## Dataset(s)
            ```yml
            - ${{ matrix.dataset }}
            ```
            ## Next Steps: 
            If you have manually checked above files and they seem to be ok, comment `[publish]` under this issue. 
            This would allow github actions to move staging files to production. 
            Feel free to close this issue once it's all complete. Thanks!
            `;
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body
            });
            

    
