name: make pr
on:
  repository_dispatch: 
    types: [pr]
  schedule:
    - cron: 5 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: develop
          delete-branch: false
          title: '[Example] Update report'
          labels: |
            report
          assignees: sptkl
          reviewers: sptkl
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
