name: make pr
on:
  repository_dispatch: 
    types: [pr]
  schedule:
    - cron: 5 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"                                 # If blank, default: triggered branch
          destination_branch: "master"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_reviewer: "sptkl"                         # Comma-separated list (no spaces)
          pr_assignee: "sptkl"                         # Comma-separated list (no spaces)
          pr_label: "revieq"                               # Comma-separated list (no spaces)
          pr_draft: false                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
