name: Test - github hosted database
on:
  push:
  
jobs: 
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
      - id: python
        shell: python
        run: |
          import os
          message='''
          {
            "conf": {
              "bucket": "XXXXX",
              "dataset": "XXXXX",
              "file_path": "XXXXXXX/.gitkeep",
              "project_id": "XXXXXX",
              "table_id": ""
            },
            "dag_id": "XXXXXX",
            "dag_run_id": "manual__2022-08-17T21:03:12.691901+00:00",
            "end_date": null,
            "execution_date": "2022-08-17T21:03:12.691901+00:00",
            "external_trigger": true,
            "logical_date": "2022-08-17T21:03:12.691901+00:00",
            "start_date": null,
            "state": "queued"
          }
          '''
          message = message.replace("\n", "%0A").replace("%", "%25").replace("\r", "%0D")
          os.system(f"echo ::set-output name=stdout::'{message}'")
      - run: echo '${{ steps.python.outputs.stdout }}'
          
