name: Build

on: [push]

jobs:
  Build:
    services:
      pg:
        image: postgis/postgis:11-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    name: Building ...
    runs-on: ubuntu-20.04
    env:
      BUILD_ENGINE: postgresql://postgres:postgres@pg:5432/postgres
    steps:
        - uses: actions/checkout@v2

        - name: Initialize
          run: docker build -t facdb .
        
        - name: test
          run: docker run --rm facdb python3 app.py