name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    permissions:
      contents: 'write'
      id-token: 'write'
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      revision: ${{ steps.output.outputs.revision }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          changelog: false
      
      - name: get latest tag
        run: |
          LATEST_TAG=$(gh release list --limit 1 | awk '{print $2}' | head -n 1)
          echo "Latest tag is: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      
      - name: Release
        if: ${{ env.LATEST_TAG != env.REVISION }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: output
        id: output
        run: |
          echo "revision=${{ env.REVISION }}" >> "$GITHUB_OUTPUT"
    
  deploy:
    runs-on: ubuntu-latest
    needs: bump-version
    steps: 
      - name: Check out
        run: |
          echo ${{ needs.bump-version.outputs.revision }}
  
