name: Test - github hosted database
on:
  push:
  
jobs: 
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
      - id: plan
        run: python -c "print('%25 %25 %0D %0D %0A %0A')"
      - run: echo '%25 %25 %0D %0D %0A %0A'
