name: Test - github hosted database
on:
  push:
  
jobs: 
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
      - id: plan
        run: python -c "print('%25 %25 %0D %0D %0A %0A')"
      - run: echo '%25 %25 %0D %0D %0A %0A'
      - id: test
        run: |
          message='{%0A  "conf": {%0A    "bucket": "tfd-sandbox",%0A    "dataset": "recall_mock",%0A    "file_path": "data-dropbox-template/dropbox/recall_mock/fake_reason_2022-08-15.csv",%0A    "project_id": "tfddevelopment",%0A    "table_id": "fake_reason_2022_08_15"%0A  },%0A  "dag_id": "example_tutorial",%0A  "dag_run_id": "manual__2022-08-17T22:01:45.336816+00:00",%0A  "end_date": null,%0A  "execution_date": "2022-08-17T22:01:45.336816+00:00",%0A  "external_trigger": true,%0A  "logical_date": "2022-08-17T22:01:45.336816+00:00",%0A  "start_date": null,%0A  "state": "queued"%0A}%0A'
          echo ::set-output name=stdout::$message
      - run: echo '${{ steps.test.outputs.stdout }}'
