name: Test - github hosted database
on:
  push:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Would you like to rebuild DevDB? (yes/no) If no, set archive or export to yes.'
        required: false
        default: 'yes'
      export:
        description: 'Would you like to export the outputs and QAQC to DigitalOcean? (yes/no)'
        required: true
        default: 'no'
      archive:
        description: 'Would you like to archive developments and dcp_housing to EDM-DATA? (yes/no)'
        required: false
        default: 'no'
jobs: 
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
      - name: test input 
        run: echo "${{  github.event.inputs.archive }}"
      - name: test another
        run: echo "${{  github.event.inputs.export }}"
