name: Build

on: [push]

jobs:
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Initialize
          run: docker-compose up -d
        
        - name: Check on Services
          run: docker-compose ps
        
        - name: test connection
          run: psql postgresql://postgres:postgres@0.0.0.0:5432/postgres -c "select 1 as a"
           
        - name: Run Pipeliens
          run: docker-compose exec -T facdb python3 app.py
