name: Test - github hosted database
on:
  push:
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Would you like to rebuild DevDB? (yes/no) If no, set archive or export to yes.'
        required: false
        default: 'yes'
      export:
        description: 'Would you like to export the outputs and QAQC to DigitalOcean? (yes/no)'
        required: true
        default: 'no'
      archive:
        description: 'Would you like to archive developments and dcp_housing to EDM-DATA? (yes/no)'
        required: false
        default: 'no'
jobs: 
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
      - name: config
        id: config
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            echo "::set-output name=rebuild::${{  github.event.inputs.archive }}"
            echo "::set-output name=archive::${{  github.event.inputs.archive }}"
            echo "::set-output name=export::${{  github.event.inputs.export }}"
          else
            echo "::set-output name=rebuild::yes"
            echo "::set-output name=archive::no"
            echo "::set-output name=export::no"
          fi
          
      - name: test input 
        run: echo "${{  steps.config.outputs.rebuild }}"
        
      - name: test another
        if: steps.config.outputs.rebuild == 'yes'
        run: echo "${{  github.event.inputs.export }}"
