name: Workflow - ${{ github.event.client_payload.cadence }}

on:
  repository_dispatch:
    types: [trigger]

jobs:
  custom-job:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Print custom payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Custom data: ${{ github.event.client_payload.custom_data }}"
